name: Portfolio Prod-Deployment

on:
  push:
    branches:
      - "production"

jobs:
  build:
    name: Bauen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - name: Abhängigkeiten laden
        run: npm i
      - name: Projekt bauen
        run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: result
          path: dist/

  deploy:
    name: Deployen
    runs-on: ubuntu-latest
    steps:
      - name: Vorbereiten
        uses: actions/checkout@v4

      - name: Hole gebautes Ergebnis
        uses: actions/download-artifact@master
        with:
          name: result
          path: dist/

      - name: FTP-Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: bono-fox.de
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: backend/prod/
    needs: [build]
