name: PR testen

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    name: Tests ausführen
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Abhängigkeiten laden
        run: npm i

      - name: Alle Tests ausführen
        run: npm run test:cov

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
